-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SIXFRIENDS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SIXFRIENDS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIXFRIENDS` DEFAULT CHARACTER SET utf8 ;
USE `SIXFRIENDS` ;

-- -----------------------------------------------------
-- Table `SIXFRIENDS`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIXFRIENDS`.`USUARIOS` (
  `USU_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `USU_TELEFONE` VARCHAR(11) NOT NULL,
  `USU_NOME` VARCHAR(60) NOT NULL,
  `USU_SENHA` VARCHAR(100) NOT NULL,
  `USU_EMAIL` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`USU_CODIGO`),
  UNIQUE INDEX `USU_COD_UNIQUE` (`USU_CODIGO` ASC) VISIBLE,
  UNIQUE INDEX `USU_EMAIL_UNIQUE` (`USU_EMAIL` ASC) VISIBLE,
  UNIQUE INDEX `USU_TELEFONE_UNIQUE` (`USU_TELEFONE` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIXFRIENDS`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIXFRIENDS`.`CATEGORIA` (
  `CAT_CODIGO` INT UNSIGNED NOT NULL,
  `CAT_TIPO` ENUM('EVENTO', 'GRUPO', 'TODOS') NOT NULL,
  `CAT_NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CAT_CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIXFRIENDS`.`GRUPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIXFRIENDS`.`GRUPO` (
  `GRU_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `GRU_NOME` VARCHAR(45) NOT NULL,
  `GRU_CAT_CODIGO` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`GRU_CODIGO`, `GRU_CAT_CODIGO`),
  INDEX `fk_GRUPO_CATEGORIA1_idx` (`GRU_CAT_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_GRUPO_CATEGORIA1`
    FOREIGN KEY (`GRU_CAT_CODIGO`)
    REFERENCES `SIXFRIENDS`.`CATEGORIA` (`CAT_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIXFRIENDS`.`EVENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIXFRIENDS`.`EVENTOS` (
  `EVE_CODIGO` INT UNSIGNED NOT NULL,
  `EVE_DATA` DATETIME NOT NULL,
  `EVE_LOCAL` VARCHAR(512) NOT NULL,
  `EVE_NOME` VARCHAR(45) NOT NULL,
  `EVE_QUANTIDADE_DE_PARTICIPANTES` INT NOT NULL,
  `EVE_CAT_CODIGO` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`EVE_CODIGO`, `EVE_CAT_CODIGO`),
  UNIQUE INDEX `EVE_CODIGO_UNIQUE` (`EVE_CODIGO` ASC) VISIBLE,
  INDEX `fk_EVENTO_CATEGORIA1_idx` (`EVE_CAT_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_EVENTO_CATEGORIA1`
    FOREIGN KEY (`EVE_CAT_CODIGO`)
    REFERENCES `SIXFRIENDS`.`CATEGORIA` (`CAT_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIXFRIENDS`.`USUARIOS_DOS_GRUPOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIXFRIENDS`.`USUARIOS_DOS_GRUPOS` (
  `UDG_USU_CODIGO` INT NOT NULL,
  `UDG_GRU_CODIGO` INT NOT NULL,
  PRIMARY KEY (`UDG_USU_CODIGO`, `UDG_GRU_CODIGO`),
  INDEX `fk_USUARIO_has_GRUPO_GRUPO1_idx` (`UDG_GRU_CODIGO` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_GRUPO_USUARIO_idx` (`UDG_USU_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_GRUPO_USUARIO`
    FOREIGN KEY (`UDG_USU_CODIGO`)
    REFERENCES `SIXFRIENDS`.`USUARIOS` (`USU_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_GRUPO_GRUPO1`
    FOREIGN KEY (`UDG_GRU_CODIGO`)
    REFERENCES `SIXFRIENDS`.`GRUPO` (`GRU_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIXFRIENDS`.`USUARIOS_DOS_EVENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIXFRIENDS`.`USUARIOS_DOS_EVENTOS` (
  `UDE_USU_CODIGO` INT NOT NULL,
  `UDE_EVE_CODIGO` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`UDE_USU_CODIGO`, `UDE_EVE_CODIGO`),
  INDEX `fk_USUARIO_has_EVENTO_EVENTO1_idx` (`UDE_EVE_CODIGO` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_EVENTO_USUARIO1_idx` (`UDE_USU_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_EVENTO_USUARIO1`
    FOREIGN KEY (`UDE_USU_CODIGO`)
    REFERENCES `SIXFRIENDS`.`USUARIOS` (`USU_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_EVENTO_EVENTO1`
    FOREIGN KEY (`UDE_EVE_CODIGO`)
    REFERENCES `SIXFRIENDS`.`EVENTOS` (`EVE_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIXFRIENDS`.`GRUPOS_DOS_EVENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIXFRIENDS`.`GRUPOS_DOS_EVENTOS` (
  `GDE_EVE_CODIGO` INT UNSIGNED NOT NULL,
  `GDE_GRU_CODIGO` INT NOT NULL,
  PRIMARY KEY (`GDE_EVE_CODIGO`, `GDE_GRU_CODIGO`),
  INDEX `fk_EVENTOS_has_GRUPO_GRUPO1_idx` (`GDE_GRU_CODIGO` ASC) VISIBLE,
  INDEX `fk_EVENTOS_has_GRUPO_EVENTOS1_idx` (`GDE_EVE_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_EVENTOS_has_GRUPO_EVENTOS1`
    FOREIGN KEY (`GDE_EVE_CODIGO`)
    REFERENCES `SIXFRIENDS`.`EVENTOS` (`EVE_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENTOS_has_GRUPO_GRUPO1`
    FOREIGN KEY (`GDE_GRU_CODIGO`)
    REFERENCES `SIXFRIENDS`.`GRUPO` (`GRU_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
